import warnings

warnings.simplefilter('ignore')

import torch
import torch.nn as nn
from lpips import LPIPS
from arch.vgg_arch import PerceptualVGG

__all__ = [
    "LPIPSLoss",
    "TVLoss",
    "PerceptualLoss"
]


# Source code reference from `https://github.com/richzhang/PerceptualSimilarity`.
class LPIPSLoss(nn.Module):
    r"""Learned Perceptual Image Patch Similarity (LPIPS) metric"""

    def __init__(self, loss_weight: float, lpips_loss_arch: str = "vgg") -> None:
        super(LPIPSLoss, self).__init__()
        self.loss_weight = loss_weight
        self.model = LPIPS(net=lpips_loss_arch, verbose=False).eval()

    def forward(self,
                source: torch.Tensor,
                target: torch.Tensor,
                normalize: bool = True,
                val=False, **ignore_kwargs
                ) -> torch.Tensor:
        if source.dim() > 4:
            # [batch_size, channels, num_frames, height, width] -> [batch_frame, channels, height, width]
            source = source.permute(0, 2, 1, 3, 4).flatten(0, 1)
            target = target.permute(0, 2, 1, 3, 4).flatten(0, 1)

        lpips_loss = torch.mean(self.model(source, target, normalize=normalize))
        if val:
            return lpips_loss
        else:
            return lpips_loss * self.loss_weight


# Source code reference from `https://github.com/jxgu1016/Total_Variation_Loss.pytorch/blob/master/TVLoss.py`.
class TVLoss(nn.Module):
    r"""Regularization loss based on Li FeiFei."""

    def __init__(self, weight: torch.Tensor) -> None:
        """The weight information of loss is based on the image information generated by the generator.

        Args:
            weight (tensor): Fake high resolution image weight.
        """
        super(TVLoss, self).__init__()
        self.weight = weight

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        batch_size = x.size()[0]
        h_x = x.size()[2]
        w_x = x.size()[3]
        count_h = self.tensor_size(x[:, :, 1:, :])
        count_w = self.tensor_size(x[:, :, :, 1:])
        h_tv = torch.pow((x[:, :, 1:, :] - x[:, :, :h_x - 1, :]), 2).sum()
        w_tv = torch.pow((x[:, :, :, 1:] - x[:, :, :, :w_x - 1]), 2).sum()
        tv_loss = self.weight * 2 * (h_tv / count_h + w_tv / count_w) / batch_size

        return tv_loss

    @staticmethod
    def tensor_size(t):
        return t.image_size()[1] * t.image_size()[2] * t.image_size()[3]


class PerceptualLoss(nn.Module):
    """Perceptual loss with commonly used style loss.
    REFERENCE: https://github.com/open-mmlab/mmediting/
    Args:
        layers_weights (dict): The weight for each layer of vgg feature.
            Here is an example: {'4': 1., '9': 1., '18': 1.}, which means the
            5th, 10th and 18th feature layer will be extracted with weight 1.0
            in calculating losses.
        vgg_type (str): The type of vgg network used as feature extractor.
            Default: 'vgg19'.
        use_input_norm (bool):  If True, normalize the input image in vgg.
            Default: True.
        perceptual_weight (float): If `perceptual_weight > 0`, the perceptual
            loss will be calculated and the loss will be multiplied by the
            weight. Default: 1.0.
        style_weight (float): If `style_weight > 0`, the style loss will be
            calculated and the loss will be multiplied by the weight.
            Default: 1.0.
        norm_img (bool): If True, the image will be normed to [0, 1]. Note that
            this is different from the `use_input_norm` which norm the input in
            in forward function of vgg according to the statistics of dataset.
            Importantly, the input image must be in range [-1, 1].
        pretrained (str): Path for pretrained weights. Default:
            'torchvision://vgg19'.
        criterion (str): Criterion type. Options are 'l1' and 'mse'.
            Default: 'l1'.
    """

    def __init__(self,
                 layer_weights,
                 vgg_type='vgg19',
                 use_input_norm=True,
                 perceptual_weight=1.0,
                 style_weight=0.0,
                 norm_img=False,
                 criterion='l1',
                 reduction='mean'):
        super().__init__()
        self.norm_img = norm_img
        self.perceptual_weight = perceptual_weight
        self.style_weight = style_weight
        self.layer_weights = layer_weights
        self.reduction = reduction
        self.vgg = PerceptualVGG(
            layer_name_list=list(layer_weights.keys()),
            vgg_type=vgg_type,
            use_input_norm=use_input_norm)

        criterion = criterion.lower()
        if criterion == 'l1':
            self.criterion = torch.nn.L1Loss(reduction=reduction)
        elif criterion == 'mse':
            self.criterion = torch.nn.MSELoss(reduction=reduction)
        else:
            raise NotImplementedError(
                f'{criterion} criterion has not been supported in'
                ' this version.')

    def forward(self, x, gt, val=False, **ignore_kwargs):

        if x.dim() > 4:
            x = torch.cat(x.unbind(2), dim=0)
            gt = torch.cat(gt.unbind(2), dim=0)

        """Forward function.
        Args:
            x (Tensor): Input tensor with shape (n, c, h, w).
            gt (Tensor): Ground-truth tensor with shape (n, c, h, w).
        Returns:
            Tensor: Forward results.
        """

        if self.norm_img:
            x = (x + 1.) * 0.5
            gt = (gt + 1.) * 0.5
        # extract vgg features
        x_features = self.vgg(x)
        gt_features = self.vgg(gt.detach())

        loss = 0

        # calculate perceptual loss
        percep_loss = 0
        for k in x_features.keys():
            percep_loss += self.criterion(
                x_features[k], gt_features[k]) * self.layer_weights[k]
        percep_loss *= self.perceptual_weight
        loss += percep_loss

        # calculate style loss
        if self.style_weight > 0:
            style_loss = 0
            for k in x_features.keys():
                style_loss += self.criterion(
                    self._gram_mat(x_features[k]),
                    self._gram_mat(gt_features[k])) * self.layer_weights[k]
            style_loss *= self.style_weight
            loss += style_loss
        return loss

    def _gram_mat(self, x):
        """Calculate Gram matrix.
        Args:
            x (torch.Tensor): Tensor with shape of (n, c, h, w).
        Returns:
            torch.Tensor: Gram matrix.
        """
        (n, c, h, w) = x.size()
        features = x.view(n, c, w * h)
        features_t = features.transpose(1, 2)
        gram = features.bmm(features_t) / (c * h * w)
        return gram
