video_spec:
  fps: 25
  size: [192, 192]

audio_spec:
  mel_step_size: 16
  sample_rate: 16000

window_size: 5

num_samples: 100





classifier:
  hidden_dim: 512
  dropout: 0.1
  num_encoder_layers: 3
  num_cross_layers: 1

optim:
  type: Adam
  lr: 1.0e-5
  betas: [0.9, 0.999]

#scheduler:
#  type: MultiStepLR
#  milestones: [0.8]
#  gamma: 0.5

scheduler:
  type: CosineAnnealingLR
  eta_min: 1.0e-5


losses:
  pos:
    type: CrossEntropyLoss
    label_smoothing: 0.1
