manual_seed: 1234

# weight: runs/train_lipsync_mix_lrs2/weights/wav2lip.pt
# weight: runs/train_lipsync_lrs2_tuning/weights/wav2lip.pt
# weight: runs/train_lipsync_mix_lrs2_l1lpips/weights/wav2lip_sync.pt
weight: ~
# ckpt: runs/train_lipsync_mix_lrs2_l1/ckpt/latest.pt
use_amp: false
use_mask: true
scale_lr: false
data_spec:
  num_samples: 1
  eval_samples: 2
  mode: h5  # h5 or image
  prefetch_factor: 8  # prefetch_factor for dataloader (default: 2)
  verbose: False  # might be super-slow for large scale datasets
  window_size: 5
  aug:
    flip:
      p: 0.5
  normalize:
    std: [ 0.5, 0.5, 0.5 ]
    mean: [ 0.5, 0.5, 0.5 ]
  # dataset extension factor
  ft_ext: 30
  hdtf_ext: 30

video_spec:
  fps: 25
  size: [ 256, 256 ]

audio_spec:
  mel_step_size: 16
  sample_rate: 16000


optim:
  type: Adam
  lr: 1.0e-4
  betas: [ 0.9, 0.95 ]

model:
  norm: bn
  sigmoid: false
  finetune: false

# scheduler:
#   type: PolynomialLR
#   power: 0.9


scheduler:
  type: CosineAnnealingLR
#   eta_min: 1.0e-7


losses:
  recon_loss:
    type: PixelLoss
    criterion: l1
    loss_weight: 1
  perceptual_loss:
    type: LPIPSLoss
    loss_weight: 0.1
    lpips_loss_arch: vgg

  sync_loss:
    type: SyncLoss
    ckpt_path: runs/train_syncnet_mix_lrs2/weights/syncnet.pt
    loss_weight: 0.07
