manual_seed: 1234

data_spec:
  mode: 'h5'  # h5 or image
  prefetch_factor: 8  # prefetch_factor for dataloader (default: 2)
  verbose: False  # might be super-slow for large scale datasets
  window_size: 5

  aug:
    rotate:
      degrees: 10
      center: [ 128, 128 ]
    sharpness:
      sharpness_factor: 2
      p: 0.1
    flip:
      p: 0.3
    contrast:
      p: 0.1


video_spec:
  fps: 25
  size: [ 256, 256 ]
  crop_pad: [ 16, -16, 48, -48 ]
  random_crop: true

audio_spec:
  mel_step_size: 16
  sample_rate: 16000

num_samples: 500
eval_samples: 50

optim:
  type: Adam
  lr: 1.0e-5
  betas: [ 0.9, 0.999 ]

#scheduler:
#  type: MultiStepLR
#  milestones: [0.8]
#  gamma: 0.5

scheduler:
  type: CosineAnnealingLR
  eta_min: 1.0e-7


losses:
  recon_loss:
    type: PixelLoss
    criterion: l1
    loss_weight: 1
  perceptual_loss:
    type: LPIPSLoss
    loss_weight: 0.1
    lpips_loss_arch: 'vgg'
  #  perceptual_loss:
  #    type: PerceptualLoss
  #    layer_weights: { '2': 0.1, '7': 0.1, '16': 1, '25': 1, '34': 1, }
  #    vgg_type: 'vgg19'
  #    norm_img: False
  #    criterion: 'l1'
  #    perceptual_weight: 1

  sync_loss:
    type: SyncLoss
    ckpt_path: runs/train_syncnet_hdtf_ori_expert/weights/syncnet.pt
    loss_weight: 0
