manual_seed: 1234
g_weight: null
d_weight: null

warmup_lr: true
warmup_iters: 0.1




data_spec:
  mode: image
  num_samples: 300
  eval_samples: 50
  window_size: 5
  prefetch_factor: 8  # prefetch_factor for dataloader (default: 2)
  train_size: 256
  eval_size: 256
  aug:
    rotate:
      degrees: 10
      center: [ 128, 128 ]
    flip:
      p: 0.5
  normalize:
    std: [ 0.5, 0.5, 0.5 ]
    mean: [ 0.5, 0.5, 0.5 ]

video_spec:
  fps: 25
  size: [ 256, 256 ]

audio_spec:
  mel_step_size: 16
  sample_rate: 16000

model:
  vq_config_path: config/vqgan.yml
  use_audio_reference: false
  use_image_reference: false
  vq_state_dict: pretrained/vq_model_512_256.pt


optim:
  type: AdamW
  lr: !!float 1.5e-4  # adjust by effective bsz as mage
  weight_decay: 0.05
  betas: [ 0.9, 0.999 ]

scheduler:
 type: MultiStepLR
 milestones: [ 1 ]
 gamma: 1

#scheduler:
#  type: PolynomialLR
#  power: 0.9

# scheduler:
#   type: CosineAnnealingLR
#   eta_min: 1.0e-5


losses: ~