manual_seed: 1234

data_spec:
  mode: 'h5'  # h5 or image
  prefetch_factor: 8  # prefetch_factor for dataloader (default: 2)
  verbose: False  # might be super-slow for large scale datasets
  window_size: 5

  aug:
    rotate:
      degrees: 5
      center: [ 128, 128 ]
    sharpness:
      sharpness_factor: 2
      p: 0.1
    flip:
      p: 0.1
    contrast:
      p: 0.1


video_spec:
  fps: 25
  size: [ 256, 256 ]

audio_spec:
  mel_step_size: 16
  sample_rate: 16000


num_samples: 1000
eval_samples: 50

optim:
  type: Adam
  lr: 1.0e-5
  betas: [ 0.9, 0.999 ]

scheduler:
  type: MultiStepLR
  milestones: [ 0.4, 0.8 ]
  gamma: 0.5

#scheduler:
#  type: CosineAnnealingLR
#  eta_min: 1.0e-5


losses:
  sync_loss:
    type: CosineLoss
    loss_weight: 1
