manual_seed: 1234
g_weight: null
d_weight: null
use_amp: false
gan_starts: 0
clip_grad: 1
data_spec:
  mode: h5
  num_samples: 1
  eval_samples: 1
  window_size: 5
  prefetch_factor: 8  # prefetch_factor for dataloader (default: 2)
  train_size: 256
  eval_size: 256
  aug:
    flip:
      p: 0.5
  normalize:
    std: [ 0.5, 0.5, 0.5 ]
    mean: [ 0.5, 0.5, 0.5 ]

video_spec:
  fps: 25
  size: [ 256, 256 ]

audio_spec:
  mel_step_size: 16
  sample_rate: 16000

g_model:
  gt_resolution: 256
  norm_type: 'gn'
  act_type: 'silu'
  codebook_scale: 32
  codebook_size: 512
  emb_dim: 256
  quantizer_type: nearest

d_model:
  num_in_ch: 3

optim:
  - type: Adam
    lr: !!float 1.0e-4
    betas: [ 0.9, 0.999 ]
  - type: Adam
    lr: !!float 4.0e-4
    betas: [ 0.9, 0.999 ]

scheduler:
  type: CosineAnnealingLR
  eta_min: 1.0e-4


losses:
  recon_loss:
    type: PixelLoss
    criterion: l1
    loss_weight: 1
  perceptual_loss:
    type: LPIPSLoss
    loss_weight: 1
    lpips_loss_arch: 'vgg'
  # consistency_loss:
  #   type: ConsistencyLoss
  #   loss_weight: 1
  codebook_loss:
    loss_weight: 1

  adversarial:
    type: GANLoss
    gan_type: hinge
    loss_weight: 0.1  # using adaptive loss_weight
