manual_seed: 1234
g_weight: null
d_weight: null
#ckpt: runs/train_vqgan_ffhq_femasr/ckpt/latest.pt
gan_starts: 0
data_spec:
  prefetch_factor: 8  # prefetch_factor for dataloader (default: 2)
  num_eval: 200
  aug:
    train_resize:
      size: 256
    flip:
      p: 0.5
    color_jitter:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
    random_crop:
      size: 256
      pad_if_needed: true
      padding_mode: reflect
    #    scale_jitter:
    #      target_size: [ 256, 256 ]
    #      scale_range: [ 0.75, 1.25 ]
    #    random_affine:
    #      degrees: [ -45, 45 ]
    #      translate: [ 0.1, 0.3 ]
    #      scale: [ 0.75, 1.25 ]
    #      fill: 255
    normalize:
      std: [ 0.5, 0.5, 0.5 ]
      mean: [ 0.5, 0.5, 0.5 ]

    # only used in eval set
    eval_resize:
      size: 256

#g_model:
#  img_size: 256
#  nf: 64
#  ch_mult: [ 1, 2, 2, 4, 4, 8 ]
#  quantizer: nearest
#  codebook_size: 1024
#  image_norm: false

#d_model:
#  nc: 3
#  ndf: 64
#  n_layers: 4

g_model:
  gt_resolution: 256
  norm_type: 'gn'
  act_type: 'silu'
  codebook_params: # has to order from low to high
    - [ 32, 1024, 512 ]

d_model:
  num_in_ch: 3

optim:
  - type: Adam
    lr: 1.0e-4
    betas: [ 0.9, 0.999 ]
  - type: Adam
    lr: 4.0e-4
    betas: [ 0.9, 0.999 ]

scheduler:
  type: MultiStepLR
  milestones: [ 0.4, 0.8]
  gamma: 0.5

#scheduler:
#  type: PolynomialLR
#  power: 0.9

#scheduler:
#  type: CosineAnnealingLR
#  eta_min: 1.0e-7


losses:
  recon_loss:
    type: PixelLoss
    criterion: l1
    loss_weight: 1
  perceptual_loss:
    type: LPIPSLoss
    loss_weight: 1
    lpips_loss_arch: 'vgg'
  #  perceptual_loss:
  #    type: PerceptualLoss
  #    layer_weights: { '2': 0.1, '7': 0.1, '16': 1, '25': 1, '34': 1, }
  #    vgg_type: 'vgg19'
  #    norm_img: False
  #    criterion: 'l1'
  #    perceptual_weight: 1


  codebook_loss:
    loss_weight: 1

  adversarial:
    type: GANLoss
    gan_type: hinge
    loss_weight: 0.1  # using adaptive loss_weight
